[project]
name = "photosharingapp-11-9-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.121.1",
    "imagekitio>=4.2.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
